"""
This type stub file was generated by pyright.
"""

__all__ = ['Subroutine']
class Subroutine:
    '''
        This class represents a program subroutine.
    '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def index(self) -> int:
        '''
            int: The index of the subroutine.
        '''
        ...
    
    @property
    def name(self) -> str:
        '''
            str: The name of the subroutine.
        '''
        ...
    


