"""
This type stub file was generated by pyright.
"""

__all__ = ['UniformBlock']
class UniformBlock:
    '''
        UniformBlock
    '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def binding(self) -> int:
        '''
            int: The binding of the uniform block.
        '''
        ...
    
    @binding.setter
    def binding(self, binding): # -> None:
        ...
    
    @property
    def value(self) -> int:
        '''
            int: The value of the uniform block.
        '''
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    @property
    def name(self) -> str:
        '''
            str: The name of the uniform block.
        '''
        ...
    
    @property
    def index(self) -> int:
        '''
            int: The index of the uniform block.
        '''
        ...
    
    @property
    def size(self) -> int:
        '''
            int: The size of the uniform block.
        '''
        ...
    


