"""
This type stub file was generated by pyright.
"""

__all__ = ['Varying']
class Varying:
    '''
        This class represents a program varying.
    '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def number(self) -> int:
        '''
            int: The number of the varying.
        '''
        ...
    
    @property
    def name(self) -> str:
        '''
            str: The name of the varying.
        '''
        ...
    


