"""
This type stub file was generated by pyright.
"""

__all__ = ['ConditionalRender']
class ConditionalRender:
    '''
        This class represents a ConditionalRender object.

        ConditionalRender objects can only be accessed from :py:class:`Query` objects.
    '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> Literal['<ConditionalRender>']:
        ...
    
    def __enter__(self): # -> Self@ConditionalRender:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


