"""
This type stub file was generated by pyright.
"""

'''
    Mock linters.
'''
__all__ = ['mgl']
class Implementation:
    class Error(Exception):
        '''
            ModernGL Error
        '''
        filename = ...
        function = ...
        line = ...
    
    
    def strsize(self, *args) -> int:
        '''
            strsize
        '''
        ...
    
    def create_context(self, *args) -> Context:
        '''
            create_context
        '''
        ...
    
    def create_standalone_context(self, *args) -> Context:
        '''
            create_standalone_context
        '''
        ...
    


mgl = ...
