"""
This type stub file was generated by pyright.
"""

__all__ = ['Scope']
class Scope:
    '''
        This class represents a Scope object.

        Responsibilities on enter:

        - Set the enable flags.
        - Bind the framebuffer.
        - Assigning textures to texture locations.
        - Assigning buffers to uniform buffers.
        - Assigning buffers to shader storage buffers.

        Responsibilities on exit:

        - Restore the enable flags.
        - Restore the framebuffer.
    '''
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> Literal['<Scope>']:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __enter__(self): # -> Self@Scope:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


